[package]
name = "leaf-utils"
version = "0.1.0-alpha.1"

description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
atproto-plc.workspace = true
dasl.workspace = true
libsql.workspace = true
